### ISSUE TITLE
Bug: Compile fails when CoreComponents is removed.

### ISSUE THREAD

**Issue by kingdomcoding** [frankdugan3/pyro#22]
Compiling with `import MyAppWeb.CoreComponents` removed (as suggested in the installation guide) fails 'cause `show/2` and `hide/2` are missing.

The call to `show/2` and `hide/2` happen in `app.html.heex`

**Comment by frankdugan3** [comment]
I will be working on a more general solution to this in a refactor, but after checking the latest templates for Phoenix, `root.html.heex` and `app.html.heex` no longer have any calls to `show/2` or `hide/2`. The problem sort of solved itself, so I'm going to close this for now.
