### ISSUE TITLE
__on_definition__ : protocol Enumerable not implemented for nil of type Atom

### ISSUE THREAD

**Issue by dev-guy** [frankdugan3/pyro#25]
**Describe the bug**

In __on_definition__,

`Module.get_attribute(env.module, :__components__)[name][:attrs]` is returning null for my component

I'm not sure why. Does it mean my component doesn't have any attributes declared?

https://github.com/frankdugan3/pyro/blob/c9c768ac344341e620baece70a3347fbf78479a6/lib/pyro/component.ex#LL336C1-L343C31

This causes: 

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.15.0-rc.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.15.0-rc.1) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.15.0-rc.1) lib/enum.ex:4384: Enum.map/2
    (pyro 0.2.0) lib/pyro/component.ex:343: Pyro.Component.__on_definition__/6
    lib/kantan_web/controllers/auth_html.ex:2: (module)
```

**To Reproduce**
```sh
git clone https://github.com/dev-guy/phoenix-ash-svelte-flowbite.git
phoenix-ash-svelte-flowbite
git checkout lv8-issue2
mix setup
mix phx.server
```

**Expected behavior**
No error

**Additional context**

If you comment out this line:

https://github.com/dev-guy/phoenix-ash-svelte-flowbite/blob/cafd71308d49b4bb777fd6eb3d64e4c221a4f078/lib/kantan_web.ex#L97

The problem goes away. This line of code is turning everything under assets/svelte/*.svelte into a component, and it's possible that it's creating components that aren't following the rules, which would require https://github.com/woutdp/live_svelte/discussions/56 to be fixed.

I can't tell which project has the bug. Perhaps live_svelte needs to add an empty list to components' metadata. Or maybe Pyro's __on_definition__ needs to check for nil.

I'm happy to create a PR for Pyro if that's OK with you, @frankdugan3

**Comment by frankdugan3** [comment]
Yeah, the problem is on Pyro's end, line 342 of `component.ex`. Though I think instead of checking for nil, it needs to default to an empty list since things that follow process lists.

A PR would be great, sorry I didn't notice this issue for 2 days! :)
