### ISSUE TITLE
Pyro Proposal: Archetypes - Views  - Archetype Configuration - Architecture - Components - UI Actions - Navigation 

### ISSUE THREAD

**Issue by couhajjou** [frankdugan3/pyro#47]
## Proposal - Driving Concepts

Any ERP will not use more than 20 screen types. We call them archetypes. This is a human factor not a technical factor

Lets express it in functionnal programming (dsl design can wait)

Assuming we have 100 resource and 10 archetypes

| #count | function  | Language
|---|---|---|
| 10         |  archetypes()                                                   | Language: Spark DSL |
| 1000    |  view = archetype(resource, architecture)  | Language: Spark DSL |
| 1000    |   architecture = tree of components | Language: Php/HEEX/JSX/PHP |
| 50        |   component                                        | Language: HTML/JS Function (JSX) / Ideally One Tag.  |
| 1M       |   view_request = view(resource_instance) |.  |
| 200    |    navigation_item = tree of {title, ui_action} |.  |
| 2000 |    ui_action = see the action spec bellow. |.  |

an architecture is an adaptation of the view archetype to the resource, it's the device used for customizing an archetype to a specific resource.

There is a clear separation between this 2 levels
     
``` --------------------------```
 archetype                <- view types any app should have less that 20. This is a Human factor not a technical factor
 archetype_config   <- usage may dictate different type of configuraton 
 view                         <- an instance of call to the archetype function 
``` --------------------------```
 architecture.          <- built with the bricks of the design system. Hence the term architecture
 components.          <- provided by the design system
``` --------------------------```

UI Actions are defined here:

https://gist.github.com/couhajjou/abe2c01ea24d5d48db52ec84c0eed987#gistcomment-4824306

## DSL proposal
will follow
...
...

**Comment by frankdugan3** [comment]
Cross-cutting concerns, incomplete proposal, not actionable. Please split into manageable, actionable items in the appropriate library for each proposal.
