### ISSUE TITLE
Bug: broken links in readme

### ISSUE THREAD

**Issue by TwistingTwists** [frankdugan3/pyro#48]
**Describe the bug**
Links to AshPyro and PyroComponents are broken in readme

**To Reproduce**

**Expected behavior**

**Additional context**
Are AshPyro and PyroComponents open source and available?

**Comment by TwistingTwists** [comment]
💜 💜

**Comment by frankdugan3** [comment]
Thanks for reporting!

Aside from the general incompleteness of Pyro, I've recently split it into 4 repos, so the docs aren't quite all fixed yet, some code is still broken, and the 3 new libs aren't yet published to Hex.

**Comment by TwistingTwists** [comment]
I am keen on trying pyro since I am building with Ash these days.

Thank you for open sourcing all the hard work. :) Appreciate it. 

I don't know how much time you have on your hands, but setting an example repo would ease things for its adoption. It is a little unclear at the moment what ties into what and how. 

I'd happy to raise PRs / bug reports  as I go on exploring pyro.

**Comment by TwistingTwists** [comment]
Take your time. :)
